#!/usr/bin/env bash
# usage: maja-create-dtm <tile>
set -e
# Copyright (C) 2020 Brockmann Consult GmbH (info@brockmann-consult.de)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, see http://www.gnu.org/licenses/

progdir=$(readlink -f $(dirname $0))
work=$(pwd)
tile=$1

cd ${progdir}/Start-MAJA/prepare_dtm

python DTMCreation.py -s ${progdir}/srtm -t ${progdir}/dtm/tmp -w ${progdir}/swbd -o ${progdir}/dtm -k ${progdir}/map/S2A_OPER_GIP_TILPAR_MPC__20151209T095117_V20150622T000000_21000101T000000_B00.kml -g ${tile}

cd ${work}
