#!/usr/bin/env bash
# usage: maja-unzip-swbd
set -e
# Copyright (C) 2020 Brockmann Consult GmbH (info@brockmann-consult.de)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, see http://www.gnu.org/licenses/

progdir=$(readlink -f $(dirname $0))
work=$(pwd)

mkdir ${progdir}/swbd
unzip ${progdir}/swbd.zip -d ${progdir}/swbd
cd ${progdir}/swbd

for file in *.shp
do
  tile="$(basename ${file} .shp)"
  zip ${tile}.zip ${tile}.dbf ${tile}.shp ${tile}.shx
  rm -f ${tile}.dbf ${tile}.shp ${tile}.shx
done

cd ${work}
