#!/bin/sh
# usage: esa-snap-worldcover-s2-pp <source-product> <target-product>
set -e
# Copyright (C) 2019 Brockmann Consult GmbH (info@brockmann-consult.de)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, see http://www.gnu.org/licenses/


container_dem_path=${HOME}/processing/dem
container_src_path=${HOME}/processing/source
container_dst_path=${HOME}/processing/target

if [ $# -eq 3 ]
then
    dem=$1
    src=$2
    dst=$3
else
    echo "usage: $0 <dem-tile-file-name> <src-tile-file-name> <dst-tile-file-name>"
    exit 0
fi

${HOME}/snap/bin/gpt -e -c 9G -Dsnap.dataio.reader.tileHeight=732 \
  -Dsnap.dataio.reader.tileWidth=732 ${HOME}/worldcover-s2-pp.xml \
  -PsourceFileDem=${container_dem_path}/${dem} \
  -PsourceFileL1c=${container_src_path}/${src} \
  -PtargetFile=${container_dst_path}/${dst}
