#!/bin/sh
# usage: esa-snap-worldcover-s2-pp <source-product> <target-product>
set -e
# Copyright (C) 2019 Brockmann Consult GmbH (info@brockmann-consult.de)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, see http://www.gnu.org/licenses/


container_dem_path=${HOME}/processing/dem
container_src_path=${HOME}/processing/source
container_dst_path=${HOME}/processing/target

if [ $# -eq 4 ]
then
    res=$1
    dem=$2
    msi=$3
    dst=$4
else
    echo "usage: $0 <res:string> <dem:string> <msi:string> <dst:string>"
    echo
    echo "<res> The spatial resolution of the target tile, either '10m' or '20m'."
    echo "<dem> The filename of the DEM tile, e.g. 'dem_32UNE.tif'"
    echo "<msi> The filename of the MSI tile, e.g. 'S2A_MSIL1C_20191007T103021_N0208_R108_T32UNE_20191007T123034.SAFE'"
    echo "<dst> The filename of the target tile, e.g. 'dst_32UNE.tif'"
    exit 0
fi

if [ ${res} = "10m" ]
then
    h=1220
    w=1220
elif [ ${res} = "20m" ]
then
    h=610
    w=610
else
    echo "error: illegal value for parameter <res>"
    exit 1
fi

${HOME}/snap/bin/gpt -e -c 12G -Dsnap.dataio.reader.tileHeight=${h} -Dsnap.dataio.reader.tileWidth=${w} ${HOME}/worldcover-s2-pp-${res}.xml \
  -PsourceFileDem=${container_dem_path}/${dem} \
  -PsourceFileMsi=${container_src_path}/${msi} \
  -PtargetFile=${container_dst_path}/${dst}
