#!/bin/sh
# usage: esa-snap-worldcover-s2-pp <source-product> <target-product>
set -e
# Copyright (C) 2019 Brockmann Consult GmbH (info@brockmann-consult.de)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, see http://www.gnu.org/licenses/


container_dem_path=${HOME}/processing/dem
container_src_path=${HOME}/processing/source
container_dst_path=${HOME}/processing/target

if [ $# -eq 3 ]
then
    dem=$1
    msi=$2
    dst=$3
else
    echo "<dem> The filename of the DEM tile, e.g. 'dem_32UNE.tif'"
    echo "<msi> The filename of the MSI tile, e.g. 'S2A_MSIL1C_20191007T103021_N0208_R108_T32UNE_20191007T123034.SAFE'"
    echo "<dst> The filename of the target tile, e.g. 'dst_32UNE.tif'"
    exit 0
fi

${HOME}/snap/bin/gpt -e -c 12G ${HOME}/WorldCover_S2_IdePix.xml \
  -PsourceFileDem=${container_dem_path}/${dem} \
  -PsourceFileMsi=${container_src_path}/${msi} \
  -PtargetFile=${container_dst_path}/${dst}
