# Copyright (C) 2019 Brockmann Consult GmbH (info@brockmann-consult.de)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, see http://www.gnu.org/licenses/

FROM ubuntu:bionic

LABEL version="0.8"
LABEL description="Ubuntu Linux with Sentinel Toolboxes, IdePix and Sentinel-2 atmospheric correction."

# Update the Linux system and install prerequisites
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y apt-utils
RUN apt-get install -y sudo
RUN apt-get install -y libgfortran3
RUN apt-get install -y wget
RUN apt-get autoremove
RUN apt-get autoclean

# Create user "worldcover"
RUN adduser --disabled-password --gecos '' worldcover
RUN adduser worldcover sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Execute all commands below as user "worldcover"
USER worldcover

WORKDIR /home/worldcover
RUN mkdir -p processing/dem
RUN mkdir -p processing/source
RUN mkdir -p processing/target

# Fetch the SNAP installer script from ESA
ADD esa-snap_all_unix_7_x.sh esa-snap_all_unix_7_x.sh
# Fetch the SNAP auxiliary data from ESA
RUN wget http://step.esa.int/auxdata/watermask/images/50m.zip
RUN wget http://step.esa.int/auxdata/watermask/images/150m.zip
RUN wget http://step.esa.int/auxdata/watermask/images/GC_water_mask.zip
RUN wget http://step.esa.int/auxdata/watermask/images/MODIS_north_water_mask.zip
RUN wget http://step.esa.int/auxdata/watermask/images/MODIS_south_water_mask.zip

# Add scripts for updating and installing modules
ADD esa-snap-update-modules esa-snap-update-modules
ADD esa-snap-install-module esa-snap-install-module
ADD esa-snap-install-modules esa-snap-install-modules
ADD modules-install.txt modules-install.txt

# Add GPT wrapper script and graph
ADD worldcover-s2-pp worldcover-s2-pp
ADD WorldCover-S2-IdePix-20m.xml WorldCover-S2-IdePix-20m.xml
ADD WorldCover-S2-IdePix-60m.xml WorldCover-S2-IdePix-60m.xml

# Make all scripts executable by user "worldcover"
RUN sudo chown -R worldcover /home/worldcover
RUN chmod ug+x esa-snap*
RUN chmod ug+x worldcover-s2-pp

# Run SNAP installation script
RUN ./esa-snap_all_unix_7_x.sh -q

# Update all SNAP modules
RUN ./esa-snap-update-modules

# Install additional modules
RUN ./esa-snap-install-modules
# Install auxiliary data
RUN mkdir -p .snap/auxdata/watermask
RUN mv 50m.zip .snap/auxdata/watermask
RUN mv 150m.zip .snap/auxdata/watermask
RUN mv GC_water_mask.zip .snap/auxdata/watermask
RUN mv MODIS_north_water_mask.zip .snap/auxdata/watermask
RUN mv MODIS_south_water_mask.zip .snap/auxdata/watermask

# Customize Java VM settings
RUN rm -f snap/bin/gpt.vmoptions
ADD gpt.vmoptions snap/bin/gpt.vmoptions
RUN sudo chown worldcover snap/bin/gpt.vmoptions

# Cleanup
RUN rm -f esa-snap*

# Environment
ENV LD_LIBRARY_PATH .

# Run SNAP command line tool (for initialization only)
RUN snap/bin/gpt

# Default command
CMD ["./worldcover-s2-pp"]
