#!/bin/sh
# usage: esa-snap-install-module <module>
# only works if all dependencies for <module> have already been installed
set -e
# Copyright (C) 2019 Brockmann Consult GmbH (info@brockmann-consult.de)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, see http://www.gnu.org/licenses/

terminate_snap()
{
    sleep 2
    pkill -TERM -f "snap/jre/bin/java"
}

module=${1}
status=1

${HOME}/snap/bin/snap --nosplash --nogui --modules --install ${module} 2>&1 | while read -r line
do
    if echo ${line} | grep -q "Installing ${module}"
    then
        echo ${line}
        continue
    fi
    if [ ${status} -gt 0 ] && [ "${line}" = "modules=1" ]
    then
        status=0
        continue
    fi
    if echo ${line} | grep -q "Cannot install. No match for"
    then
        terminate_snap
        if [ ${status} -eq 0 ]
        then
            echo "Installed ${module}"
        else
            echo ${line}
        fi
        exit ${status}
    fi
done
